깃헙 액션 스크립트 기반 릴리즈 생성 및 에셋 업데이트 테스트

diff --git a/.github/workflows/gh-release-test.yml b/.github/workflows/gh-release-test.yml
--- a/.github/workflows/gh-release-test.yml
+++ b/.github/workflows/gh-release-test.yml
@@ -20,16 +20,76 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          RESPONSE=$(gh api \
+          OLD_RELEASE=$(gh api \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             /repos/miridih-yhha/github-action-test/releases/latest)
-          echo "response=${RESPONSE}" >> $GITHUB_ENV
+          
+          echo "old-release=${OLD_RELEASE}" >> $GITHUB_ENV
 
-      - name: 태그와 업로드 경로 조회
+      - name: 버전업
         run: |
-          echo "response: ${{ env.response }}"
-          UPLOAD_URL=${{ fromJson(env.response).upload_url }}
-          TAG_NAME=${{ fromJson(env.response).tag_name }}
-          echo "UPLOAD_URL: ${UPLOAD_URL}"
-          echo "TAG_NAME: ${TAG_NAME}"
+          OLD_VERSION=${{ fromJson(env.old-release).tag_name }}
+          echo "OLD_VERSION: ${OLD_VERSION}"
+          
+          MAJOR=$(echo $OLD_VERSION | cut -d. -f1 | sed 's/v//')
+          MINOR=$(echo $OLD_VERSION | cut -d. -f2)
+          PATCH=$(echo $OLD_VERSION | cut -d. -f3)
+          
+          INCREMENT_TYPE=${{ inputs.VERSION_TO_UPGRADE }}
+          if [ "$INCREMENT_TYPE" == "MAJOR" ]; then
+          ((MAJOR++))
+          MINOR=0
+          PATCH=0
+          elif [ "$INCREMENT_TYPE" == "MINOR" ]; then
+          ((MINOR++))
+          PATCH=0
+          elif [ "$INCREMENT_TYPE" == "PATCH" ]; then
+          ((PATCH++))
+          else
+          echo "Invalid increment type!"
+          exit 1
+          fi
+          
+          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
+          echo "new-version=${NEW_VERSION}" >> $GITHUB_ENV
+
+      - name: 버전업 태그 생성
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          NEW_RELEASE=$(gh api \
+          --method POST \
+          -H "Accept: application/vnd.github+json" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          /repos/miridih-yhha/github-action-test/releases \
+          -f tag_name=${{ env.new-version }} \
+          -f target_commitish='main' \
+          -f name=${{ env.new-version }} \
+          -f body='${{ env.new-version }} release')
+          
+          echo "new-release=${NEW_RELEASE}" >> $GITHUB_ENV
+
+      - name: 새 릴리즈에 api.jar 에셋 업데이트
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gh api \
+          --method POST \
+          -H "Accept: application/vnd.github+json" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          /repos/miridih-yhha/github-action-test/releases/${{ fromJson(env.new-release).id }}/assets \
+          -f 'Content-Type=application/java-archive' \
+          -f asset=@api.jar
+
+      - name: 새 릴리즈에 consumer.jar 에셋 업데이트
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gh api \
+          --method POST \
+          -H "Accept: application/vnd.github+json" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          /repos/miridih-yhha/github-action-test/releases/${{ fromJson(env.new-release).id }}/assets \
+          -f 'Content-Type=application/java-archive' \
+          -f asset=@consumer.jar
